flowchart TD
    A(Syscalls) -->|ioh_t| B(I/O Manager)
    A -->|devh_t| C(Device Manager)
    A -->|dmah_t| D(DMA Manager)
    A -->|shmh_t| E(Memory Manager)
    A -->|inth_t| F(Interrupt Manager)
    A -->|taskh_t| G(Tasks Manager)

    F -->|itn| H(NVIC driver)
    F -->|exti| I(EXTI driver)
    E -->|mpu region| J(MPU driver)
    D -->|stream| K(DMA Driver)
    B -->|ioconf| L(GPIO driver)
